name: First Workflow
on: 
  workflow_dispatch
jobs: 
  my-first-job:
    name: RunFirstJob
    runs-on: ubuntu-latest
    steps: 
       - name: Print greeting
         run: echo "Hello World!"
       -name: Print goodbye
         run: echo "Done - bye!"
